# H2 DB
h2:
  datasource:
    jdbcUrl: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

#POSTGRES DB
postgres:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:15432/postgres
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver