spring:
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:15432/postgres
    username: admin
    password: password
    schema: classpath:db/sql/create-db.sql
    type: com.zaxxer.hikari.HikariDataSource # the fully-qualified name of the DataSource implementation we want to use
    hikari:
      connectionTimeout: 3000
      idleTimeout: 600000 # This property controls the maximum amount of time that a connection is allowed to sit idle in the pool.
      # This setting only applies when minimumIdle is defined to be less than maximumPoolSize.
      maxLifetime: 1800000 # This property controls the maximum lifetime of a connection in the pool. An in-use connection
      # will never be retired, only when it is closed will it then be removed.
      validationTimeout: 60000 # This property controls the maximum amount of time that a connection will be tested for aliveness.
      # This value must be less than the connectionTimeout. Lowest acceptable validation timeout is 250 ms. Default: 5000

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true