# spring profiles configuration
spring:
  profiles:
    active: @spring.active.profile@

# you can find the value of this property in the pom.xml fil
# it will be resolved in the build phase - check the build in the pom.xml file

# Please note that spring will search for application properties in classpath/config before checking
# the classpath
# check the order here : https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files