#data source configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    initialization-mode: always
    #  is marked as always as we want initialization of the database to happen on every startup.
    initialize: true
    # will mark the initialization to be true.
    data: classpath:data-postgres.sql
    schema: classpath:schema-postgres.sql

  jpa:
    show-sql: true
    #generate-ddl: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update, none)
      ddl-auto: validate
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public

github:
  user:
    api: https://api.github.com/users/%s
  repo:
    api: https://api.github.com/users/%s/repos

logging:
  level:
    ROOT: ERROR
    org.springframework: INFO
    org.spring.boot.examples.testing: DEBUG