# H2
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    hibernate:
      ddl-auto: validate
      # validate the schema, makes no changes to the database.
    show-sql: true
    properties:
      hiberanate:
        format_sql: true

#logging
logging:
  level:
    .: error
    org.springframework: INFO
    org.spring.boot.examples.jpa: DEBUG
    #show hibernate requests and values
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE