spring:
  profiles:
    active: tomcat
    #active: dbcp
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
