spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      initial-size: 15
      max-wait: 2000
      max-active: 50
      max-idle: 15
      min-idle: 8
      default-auto-commit: true
