spring:
  profiles:
    active: tomcat
    #active: dbcp
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:15432/postgres
    username: admin
    password: password


  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true